### ISSUE TITLE
probably incorrect syntax

### ISSUE THREAD

**Issue by nikhil-swamix** [minato-fourth/mini#2]
as in this line https://github.com/minato-fourth/mini/blob/fee0c5df066cf29fdffc2e20f4f85b870b1f8a77/send.ino#L134
`    else if(JoystickRight_var<-3): `
`<- is not valid in if else, it should be <=3 `
[see more info here](https://www.arduino.cc/reference/en/language/structure/control-structure/else/)
and change it else where.

**Comment by minato-fourth** [comment]
no im checking for negative value condition...like if the value is less than " -3 "

**Comment by nikhil-swamix** [comment]
> 
> 
> no im checking for negative value condition...like if the value is less than " -3 "

im sorry, i mistaken it with oops concept of c++ where -> and <- have meanings.. 😅😅😅
